# Generated by Django 4.1.5 on 2023-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboard', '0004_alter_leaderboard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='mapname',
            field=models.CharField(default='Space', max_length=31),
            preserve_default=False,
        ),
    ]
