# Generated by Django 4.1.5 on 2023-01-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_alter_question_category_alter_survey_gameidea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=15),
        ),
    ]
