# Generated by Django 4.1.5 on 2023-01-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='websiteDesign',
        ),
        migrations.AddField(
            model_name='survey',
            name='website',
            field=models.CharField(default='5', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='gamedesign',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gameidea',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gameplay',
            field=models.CharField(max_length=15),
        ),
    ]
